name: musiclooper_clean
description: MusicLooper (projet nettoyé)
publish_to: "none"

# Garde large pour rester compatible avec ta version de Dart/Flutter actuelle
environment:
  sdk: ">=3.0.0 <4.0.0"

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.3
  just_audio: ^0.10.5
  video_player: ^2.9.2
  shared_preferences: ^2.2.3
  permission_handler: ^12.0.1
  flutter_audio_capture: ^1.1.11
  youtube_player_flutter: ^9.1.2
  receive_sharing_intent: ^1.8.0
  share_plus: ^10.0.0
  path: ^1.9.0
dependency_overrides:
  audio_session: ^0.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  # On garde la version plus récente du template clean
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assure-toi que le dossier existe bien dans le projet
  assets:
    - assets/